/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTurnitinRouteImport } from './routes/_authenticated/admin.turnitin'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPortalsRouteImport } from './routes/_authenticated/admin.portals'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin.jobs'
import { Route as AuthenticatedAdminTurnitinIndexRouteImport } from './routes/_authenticated/admin.turnitin.index'
import { Route as AuthenticatedAdminTurnitinAccountIdRouteImport } from './routes/_authenticated/admin.turnitin.$accountId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTurnitinRoute =
  AuthenticatedAdminTurnitinRouteImport.update({
    id: '/turnitin',
    path: '/turnitin',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPortalsRoute =
  AuthenticatedAdminPortalsRouteImport.update({
    id: '/portals',
    path: '/portals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTurnitinIndexRoute =
  AuthenticatedAdminTurnitinIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTurnitinRoute,
  } as any)
const AuthenticatedAdminTurnitinAccountIdRoute =
  AuthenticatedAdminTurnitinAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthenticatedAdminTurnitinRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/portals': typeof AuthenticatedAdminPortalsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/turnitin': typeof AuthenticatedAdminTurnitinRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/turnitin/$accountId': typeof AuthenticatedAdminTurnitinAccountIdRoute
  '/admin/turnitin/': typeof AuthenticatedAdminTurnitinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/portals': typeof AuthenticatedAdminPortalsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/turnitin/$accountId': typeof AuthenticatedAdminTurnitinAccountIdRoute
  '/admin/turnitin': typeof AuthenticatedAdminTurnitinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/portals': typeof AuthenticatedAdminPortalsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/turnitin': typeof AuthenticatedAdminTurnitinRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/turnitin/$accountId': typeof AuthenticatedAdminTurnitinAccountIdRoute
  '/_authenticated/admin/turnitin/': typeof AuthenticatedAdminTurnitinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/admin/jobs'
    | '/admin/portals'
    | '/admin/settings'
    | '/admin/turnitin'
    | '/admin/users'
    | '/admin/'
    | '/admin/turnitin/$accountId'
    | '/admin/turnitin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/history'
    | '/admin/jobs'
    | '/admin/portals'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/admin/turnitin/$accountId'
    | '/admin/turnitin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/portals'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/turnitin'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/turnitin/$accountId'
    | '/_authenticated/admin/turnitin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/turnitin': {
      id: '/_authenticated/admin/turnitin'
      path: '/turnitin'
      fullPath: '/admin/turnitin'
      preLoaderRoute: typeof AuthenticatedAdminTurnitinRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portals': {
      id: '/_authenticated/admin/portals'
      path: '/portals'
      fullPath: '/admin/portals'
      preLoaderRoute: typeof AuthenticatedAdminPortalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/turnitin/': {
      id: '/_authenticated/admin/turnitin/'
      path: '/'
      fullPath: '/admin/turnitin/'
      preLoaderRoute: typeof AuthenticatedAdminTurnitinIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTurnitinRoute
    }
    '/_authenticated/admin/turnitin/$accountId': {
      id: '/_authenticated/admin/turnitin/$accountId'
      path: '/$accountId'
      fullPath: '/admin/turnitin/$accountId'
      preLoaderRoute: typeof AuthenticatedAdminTurnitinAccountIdRouteImport
      parentRoute: typeof AuthenticatedAdminTurnitinRoute
    }
  }
}

interface AuthenticatedAdminTurnitinRouteChildren {
  AuthenticatedAdminTurnitinAccountIdRoute: typeof AuthenticatedAdminTurnitinAccountIdRoute
  AuthenticatedAdminTurnitinIndexRoute: typeof AuthenticatedAdminTurnitinIndexRoute
}

const AuthenticatedAdminTurnitinRouteChildren: AuthenticatedAdminTurnitinRouteChildren =
  {
    AuthenticatedAdminTurnitinAccountIdRoute:
      AuthenticatedAdminTurnitinAccountIdRoute,
    AuthenticatedAdminTurnitinIndexRoute: AuthenticatedAdminTurnitinIndexRoute,
  }

const AuthenticatedAdminTurnitinRouteWithChildren =
  AuthenticatedAdminTurnitinRoute._addFileChildren(
    AuthenticatedAdminTurnitinRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminPortalsRoute: typeof AuthenticatedAdminPortalsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTurnitinRoute: typeof AuthenticatedAdminTurnitinRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminPortalsRoute: AuthenticatedAdminPortalsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTurnitinRoute: AuthenticatedAdminTurnitinRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
