/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardAiRouteImport } from './routes/_authenticated/dashboard.ai'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTurnitinRouteImport } from './routes/_authenticated/admin.turnitin'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPortalsRouteImport } from './routes/_authenticated/admin.portals'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin.jobs'
import { Route as AuthenticatedAdminApiClientsRouteImport } from './routes/_authenticated/admin.api-clients'
import { Route as AuthenticatedAdminTurnitinIndexRouteImport } from './routes/_authenticated/admin.turnitin.index'
import { Route as AuthenticatedAdminInstructorRouteImport } from './routes/_authenticated/admin.instructor'
import { Route as AuthenticatedAdminInstructorIndexRouteImport } from './routes/_authenticated/admin.instructor.index'
import { Route as AuthenticatedAdminInstructorAccountIdRouteImport } from './routes/_authenticated/admin.instructor.$accountId'
import { Route as AuthenticatedAdminInstructorAccountIdClassIdRouteImport } from './routes/_authenticated/admin.instructor.$accountId.$classId'
import { Route as ApiPublicV1JobsRouteImport } from './routes/api/public/v1/jobs'
import { Route as ApiPublicCronDispatchCallbacksRouteImport } from './routes/api/public/cron/dispatch-callbacks'
import { Route as AuthenticatedAdminTurnitinAccountIdRouteImport } from './routes/_authenticated/admin.turnitin.$accountId'
import { Route as ApiPublicV1JobsUploadUrlRouteImport } from './routes/api/public/v1/jobs.upload-url'
import { Route as ApiPublicV1JobsJobIdRouteImport } from './routes/api/public/v1/jobs.$jobId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAiRoute =
  AuthenticatedDashboardAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTurnitinRoute =
  AuthenticatedAdminTurnitinRouteImport.update({
    id: '/turnitin',
    path: '/turnitin',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPortalsRoute =
  AuthenticatedAdminPortalsRouteImport.update({
    id: '/portals',
    path: '/portals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApiClientsRoute =
  AuthenticatedAdminApiClientsRouteImport.update({
    id: '/api-clients',
    path: '/api-clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTurnitinIndexRoute =
  AuthenticatedAdminTurnitinIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTurnitinRoute,
  } as any)
const AuthenticatedAdminInstructorRoute =
  AuthenticatedAdminInstructorRouteImport.update({
    id: '/instructor',
    path: '/instructor',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInstructorIndexRoute =
  AuthenticatedAdminInstructorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminInstructorRoute,
  } as any)
const AuthenticatedAdminInstructorAccountIdRoute =
  AuthenticatedAdminInstructorAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthenticatedAdminInstructorRoute,
  } as any)
const AuthenticatedAdminInstructorAccountIdClassIdRoute =
  AuthenticatedAdminInstructorAccountIdClassIdRouteImport.update({
    id: '/$accountId/$classId',
    path: '/$accountId/$classId',
    getParentRoute: () => AuthenticatedAdminInstructorRoute,
  } as any)
const ApiPublicV1JobsRoute = ApiPublicV1JobsRouteImport.update({
  id: '/api/public/v1/jobs',
  path: '/api/public/v1/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDispatchCallbacksRoute =
  ApiPublicCronDispatchCallbacksRouteImport.update({
    id: '/api/public/cron/dispatch-callbacks',
    path: '/api/public/cron/dispatch-callbacks',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminTurnitinAccountIdRoute =
  AuthenticatedAdminTurnitinAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthenticatedAdminTurnitinRoute,
  } as any)
const ApiPublicV1JobsUploadUrlRoute =
  ApiPublicV1JobsUploadUrlRouteImport.update({
    id: '/upload-url',
    path: '/upload-url',
    getParentRoute: () => ApiPublicV1JobsRoute,
  } as any)
const ApiPublicV1JobsJobIdRoute = ApiPublicV1JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiPublicV1JobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/admin/api-clients': typeof AuthenticatedAdminApiClientsRoute
  '/admin/instructor': typeof AuthenticatedAdminInstructorRouteWithChildren
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/portals': typeof AuthenticatedAdminPortalsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/turnitin': typeof AuthenticatedAdminTurnitinRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/ai': typeof AuthenticatedDashboardAiRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/instructor/$accountId': typeof AuthenticatedAdminInstructorAccountIdRoute
  '/admin/turnitin/$accountId': typeof AuthenticatedAdminTurnitinAccountIdRoute
  '/admin/instructor/': typeof AuthenticatedAdminInstructorIndexRoute
  '/admin/instructor/$accountId/$classId': typeof AuthenticatedAdminInstructorAccountIdClassIdRoute
  '/api/public/cron/dispatch-callbacks': typeof ApiPublicCronDispatchCallbacksRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/admin/turnitin/': typeof AuthenticatedAdminTurnitinIndexRoute
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
  '/api/public/v1/jobs/upload-url': typeof ApiPublicV1JobsUploadUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/admin/api-clients': typeof AuthenticatedAdminApiClientsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/portals': typeof AuthenticatedAdminPortalsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/ai': typeof AuthenticatedDashboardAiRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/instructor/$accountId': typeof AuthenticatedAdminInstructorAccountIdRoute
  '/admin/turnitin/$accountId': typeof AuthenticatedAdminTurnitinAccountIdRoute
  '/admin/instructor/$accountId/$classId': typeof AuthenticatedAdminInstructorAccountIdClassIdRoute
  '/api/public/cron/dispatch-callbacks': typeof ApiPublicCronDispatchCallbacksRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/admin/instructor': typeof AuthenticatedAdminInstructorIndexRoute
  '/admin/turnitin': typeof AuthenticatedAdminTurnitinIndexRoute
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
  '/api/public/v1/jobs/upload-url': typeof ApiPublicV1JobsUploadUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/admin/api-clients': typeof AuthenticatedAdminApiClientsRoute
  '/_authenticated/admin/instructor': typeof AuthenticatedAdminInstructorRouteWithChildren
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/portals': typeof AuthenticatedAdminPortalsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/turnitin': typeof AuthenticatedAdminTurnitinRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/dashboard/ai': typeof AuthenticatedDashboardAiRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/admin/instructor/$accountId': typeof AuthenticatedAdminInstructorAccountIdRoute
  '/_authenticated/admin/turnitin/$accountId': typeof AuthenticatedAdminTurnitinAccountIdRoute
  '/_authenticated/admin/instructor/': typeof AuthenticatedAdminInstructorIndexRoute
  '/_authenticated/admin/instructor/$accountId/$classId': typeof AuthenticatedAdminInstructorAccountIdClassIdRoute
  '/api/public/cron/dispatch-callbacks': typeof ApiPublicCronDispatchCallbacksRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/_authenticated/admin/turnitin/': typeof AuthenticatedAdminTurnitinIndexRoute
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
  '/api/public/v1/jobs/upload-url': typeof ApiPublicV1JobsUploadUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/admin/api-clients'
    | '/admin/instructor'
    | '/admin/jobs'
    | '/admin/portals'
    | '/admin/settings'
    | '/admin/turnitin'
    | '/admin/users'
    | '/dashboard/ai'
    | '/admin/'
    | '/dashboard/'
    | '/admin/instructor/$accountId'
    | '/admin/turnitin/$accountId'
    | '/admin/instructor/'
    | '/admin/instructor/$accountId/$classId'

    | '/api/public/cron/dispatch-callbacks'
    | '/api/public/v1/jobs'
    | '/admin/turnitin/'
    | '/api/public/v1/jobs/$jobId'
    | '/api/public/v1/jobs/upload-url'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/history'
    | '/admin/api-clients'
    | '/admin/jobs'
    | '/admin/portals'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/ai'
    | '/admin'
    | '/dashboard'
    | '/admin/instructor/$accountId'
    | '/admin/turnitin/$accountId'
    | '/admin/instructor/$accountId/$classId'
    | '/api/public/cron/dispatch-callbacks'
    | '/api/public/v1/jobs'
    | '/admin/instructor'
    | '/admin/turnitin'

    | '/api/public/v1/jobs/$jobId'
    | '/api/public/v1/jobs/upload-url'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/admin/api-clients'
    | '/_authenticated/admin/instructor'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/portals'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/turnitin'
    | '/_authenticated/admin/users'
    | '/_authenticated/dashboard/ai'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/admin/instructor/$accountId'
    | '/_authenticated/admin/turnitin/$accountId'
    | '/_authenticated/admin/instructor/'
    | '/_authenticated/admin/instructor/$accountId/$classId'
    | '/api/public/cron/dispatch-callbacks'
    | '/api/public/v1/jobs'
    | '/_authenticated/admin/turnitin/'
    | '/api/public/v1/jobs/$jobId'
    | '/api/public/v1/jobs/upload-url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicCronDispatchCallbacksRoute: typeof ApiPublicCronDispatchCallbacksRoute
  ApiPublicV1JobsRoute: typeof ApiPublicV1JobsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ai': {
      id: '/_authenticated/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof AuthenticatedDashboardAiRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/turnitin': {
      id: '/_authenticated/admin/turnitin'
      path: '/turnitin'
      fullPath: '/admin/turnitin'
      preLoaderRoute: typeof AuthenticatedAdminTurnitinRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portals': {
      id: '/_authenticated/admin/portals'
      path: '/portals'
      fullPath: '/admin/portals'
      preLoaderRoute: typeof AuthenticatedAdminPortalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/instructor': {
      id: '/_authenticated/admin/instructor'
      path: '/instructor'
      fullPath: '/admin/instructor'
      preLoaderRoute: typeof AuthenticatedAdminInstructorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/api-clients': {
      id: '/_authenticated/admin/api-clients'
      path: '/api-clients'
      fullPath: '/admin/api-clients'
      preLoaderRoute: typeof AuthenticatedAdminApiClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/turnitin/': {
      id: '/_authenticated/admin/turnitin/'
      path: '/'
      fullPath: '/admin/turnitin/'
      preLoaderRoute: typeof AuthenticatedAdminTurnitinIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTurnitinRoute
    }
    '/_authenticated/admin/instructor/': {
      id: '/_authenticated/admin/instructor/'
      path: '/'
      fullPath: '/admin/instructor/'
      preLoaderRoute: typeof AuthenticatedAdminInstructorIndexRouteImport
      parentRoute: typeof AuthenticatedAdminInstructorRoute
    }
    '/_authenticated/admin/instructor/$accountId': {
      id: '/_authenticated/admin/instructor/$accountId'
      path: '/$accountId'
      fullPath: '/admin/instructor/$accountId'
      preLoaderRoute: typeof AuthenticatedAdminInstructorAccountIdRouteImport
      parentRoute: typeof AuthenticatedAdminInstructorRoute
    }
    '/_authenticated/admin/instructor/$accountId/$classId': {
      id: '/_authenticated/admin/instructor/$accountId/$classId'
      path: '/$accountId/$classId'
      fullPath: '/admin/instructor/$accountId/$classId'
      preLoaderRoute: typeof AuthenticatedAdminInstructorAccountIdClassIdRouteImport
      parentRoute: typeof AuthenticatedAdminInstructorRoute
    }
    '/api/public/v1/jobs': {
      id: '/api/public/v1/jobs'
      path: '/api/public/v1/jobs'
      fullPath: '/api/public/v1/jobs'
      preLoaderRoute: typeof ApiPublicV1JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/dispatch-callbacks': {
      id: '/api/public/cron/dispatch-callbacks'
      path: '/api/public/cron/dispatch-callbacks'
      fullPath: '/api/public/cron/dispatch-callbacks'
      preLoaderRoute: typeof ApiPublicCronDispatchCallbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/turnitin/$accountId': {
      id: '/_authenticated/admin/turnitin/$accountId'
      path: '/$accountId'
      fullPath: '/admin/turnitin/$accountId'
      preLoaderRoute: typeof AuthenticatedAdminTurnitinAccountIdRouteImport
      parentRoute: typeof AuthenticatedAdminTurnitinRoute
    }
    '/api/public/v1/jobs/upload-url': {
      id: '/api/public/v1/jobs/upload-url'
      path: '/upload-url'
      fullPath: '/api/public/v1/jobs/upload-url'
      preLoaderRoute: typeof ApiPublicV1JobsUploadUrlRouteImport
      parentRoute: typeof ApiPublicV1JobsRoute
    }
    '/api/public/v1/jobs/$jobId': {
      id: '/api/public/v1/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/public/v1/jobs/$jobId'
      preLoaderRoute: typeof ApiPublicV1JobsJobIdRouteImport
      parentRoute: typeof ApiPublicV1JobsRoute
    }
  }
}

interface AuthenticatedAdminInstructorRouteChildren {
  AuthenticatedAdminInstructorIndexRoute: typeof AuthenticatedAdminInstructorIndexRoute
  AuthenticatedAdminInstructorAccountIdRoute: typeof AuthenticatedAdminInstructorAccountIdRoute
  AuthenticatedAdminInstructorAccountIdClassIdRoute: typeof AuthenticatedAdminInstructorAccountIdClassIdRoute
}

const AuthenticatedAdminInstructorRouteChildren: AuthenticatedAdminInstructorRouteChildren =
  {
    AuthenticatedAdminInstructorIndexRoute:
      AuthenticatedAdminInstructorIndexRoute,
    AuthenticatedAdminInstructorAccountIdRoute:
      AuthenticatedAdminInstructorAccountIdRoute,
    AuthenticatedAdminInstructorAccountIdClassIdRoute:
      AuthenticatedAdminInstructorAccountIdClassIdRoute,
  }

const AuthenticatedAdminInstructorRouteWithChildren =
  AuthenticatedAdminInstructorRoute._addFileChildren(
    AuthenticatedAdminInstructorRouteChildren,
  )

interface AuthenticatedAdminTurnitinRouteChildren {
  AuthenticatedAdminTurnitinAccountIdRoute: typeof AuthenticatedAdminTurnitinAccountIdRoute
  AuthenticatedAdminTurnitinIndexRoute: typeof AuthenticatedAdminTurnitinIndexRoute
}

const AuthenticatedAdminTurnitinRouteChildren: AuthenticatedAdminTurnitinRouteChildren =
  {
    AuthenticatedAdminTurnitinAccountIdRoute:
      AuthenticatedAdminTurnitinAccountIdRoute,
    AuthenticatedAdminTurnitinIndexRoute: AuthenticatedAdminTurnitinIndexRoute,
  }

const AuthenticatedAdminTurnitinRouteWithChildren =
  AuthenticatedAdminTurnitinRoute._addFileChildren(
    AuthenticatedAdminTurnitinRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApiClientsRoute: typeof AuthenticatedAdminApiClientsRoute
  AuthenticatedAdminInstructorRoute: typeof AuthenticatedAdminInstructorRouteWithChildren
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminPortalsRoute: typeof AuthenticatedAdminPortalsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTurnitinRoute: typeof AuthenticatedAdminTurnitinRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApiClientsRoute: AuthenticatedAdminApiClientsRoute,
  AuthenticatedAdminInstructorRoute: AuthenticatedAdminInstructorRouteWithChildren,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminPortalsRoute: AuthenticatedAdminPortalsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTurnitinRoute: AuthenticatedAdminTurnitinRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAiRoute: typeof AuthenticatedDashboardAiRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAiRoute: AuthenticatedDashboardAiRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicV1JobsRouteChildren {
  ApiPublicV1JobsJobIdRoute: typeof ApiPublicV1JobsJobIdRoute
  ApiPublicV1JobsUploadUrlRoute: typeof ApiPublicV1JobsUploadUrlRoute
}

const ApiPublicV1JobsRouteChildren: ApiPublicV1JobsRouteChildren = {
  ApiPublicV1JobsJobIdRoute: ApiPublicV1JobsJobIdRoute,
  ApiPublicV1JobsUploadUrlRoute: ApiPublicV1JobsUploadUrlRoute,
}

const ApiPublicV1JobsRouteWithChildren = ApiPublicV1JobsRoute._addFileChildren(
  ApiPublicV1JobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicCronDispatchCallbacksRoute: ApiPublicCronDispatchCallbacksRoute,
  ApiPublicV1JobsRoute: ApiPublicV1JobsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
